### ISSUE TITLE
issue with travis.ci

### ISSUE THREAD

**Issue by andymaheshw** [andymaheshw/AdobeAnalytics#16]
Hi Randy, 

I saw the travis build wasn't responding correctly, is there anything I can help with?

ERROR: InvocationError: '/home/travis/build/andymaheshw/AdobeAnalytics/.tox/check/bin/flake8 src tests setup.py'
___________________________________ summary ____________________________________
ERROR:   check: commands failed

**Comment by andymaheshw** [comment]
Changed the tox file to fix it... Let me know if that works, check out the pull request.

**Comment by randyzwitch** [comment]
#18 still fails on the PEP8 syntax check. See my comments on your pull request, it might be worth just turning off the syntax checker until we've got a package worth releasing.

**Comment by randyzwitch** [comment]
Merged #18 to keep moving
