### ISSUE TITLE
Set up TravisCI testing

### ISSUE THREAD

**Issue by randyzwitch** [andymaheshw/AdobeAnalytics#6]
This is two parts, maybe I can tackle this today since a bunch of people are out of the office:

1. Writing tests: this is pretty obvious, we can write test(s) for the functions to ensure future changes don't break existing code

2. Set up TravisCI for continuous integration testing. I have a Travis account and I personal Adobe account, so we can use those credentials (so that it doesn't matter we either of us works in the future :))

**Comment by andymaheshw** [comment]
That sounds awesome. How do we setup a TravisCI account?

**Comment by randyzwitch** [comment]
If you are logged in to GitHub, then go to https://travis-ci.org/, it should transfer your credentials over. Then you just flip the switch on.

![screen shot 2016-05-31 at 10 52 33 am](https://cloud.githubusercontent.com/assets/2762787/15678863/d1f54076-271d-11e6-947b-a1adbedd0139.png)

After that, it's just a matter of adding a configuration file.

**Comment by andymaheshw** [comment]
Got it, making the travis.yml file now

**Comment by andymaheshw** [comment]
I think we can close once we merge my new branch

**Comment by randyzwitch** [comment]
I created a new branch add-auth-keys, so I think we've got the Travis part set up. Closing, we can consolidate discussion at #13
