### ISSUE TITLE
Auto-convert input types for rsid_list

### ISSUE THREAD

**Issue by randyzwitch** [andymaheshw/AdobeAnalytics#7]
It's semi-annoying to have to wrap the input for a single report suite for each function. For example:

```python
Want this:

aaa.GetBaseCurrency("zwitchdev")

Need to do:
aaa.GetBaseCurrency(rsid_list = ["zwitchdev"])
```

**Comment by andymaheshw** [comment]
How do you want to fix this?

**Comment by randyzwitch** [comment]
Going to fix this on the make-valid-package branch then merge into master, because this is annoying as hell
