### ISSUE TITLE
Implement remaining GET requests

### ISSUE THREAD

**Issue by randyzwitch** [andymaheshw/AdobeAnalytics#9]
While all of the GET functions appear to be stubbed out (nice!), the following do not work (either because they aren't implemented, use the wrong keyword names or are missing keyword arguments)

- [x] GetClassifications
- [x] GetElements
- [x] GetFeed
- [x] GetFeeds
- [x] GetMetrics
- [x] GetRealTimeReport
- [x] GetReportDescription
- [x] GetTrackingServer

@andymaheshw is this something you want to take or do you want me to implement these?

**Comment by andymaheshw** [comment]
Cool, I will work on these now. Are these all the methods we need?

**Comment by randyzwitch** [comment]
Just for the GET aspect; there's still the Queue functions remaining which require significantly more work

**Comment by andymaheshw** [comment]
Ok, Get functions are all in, can you look them over when you get a chance? 

Thanks!

**Comment by andymaheshw** [comment]
GetRealTimeReport - This method, I'm not sure whether Report.Run is the right API Endpoint (can you check this?)
 GetReportDescription - Done
 GetTrackingServer - Done

**Comment by randyzwitch** [comment]
Report.Run is the right endpoint.

Hoping to be able to write tests for these today, and closing this issue will be a big step forward!

**Comment by andymaheshw** [comment]
So excited! Let me know if they need to be reworked, happy to work with the tests. Let's keep it going!

**Comment by andymaheshw** [comment]
Hey Randy, What's the plan for our testing framework, should I look into pytest? Thanks!

**Comment by randyzwitch** [comment]
My apologies Andy, life sort of got in the way of this :)

I think pytest is a great idea. Ultimately, the framework matters much less than actually having tests at all.

I can probably get back to this mid-week, so if you want to take a shot first, I can then fill in other tests as needed.
